import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  image: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "flex-end",
  },
  regWrapper: {
    marginTop: "auto",
    position: "relative",
    alignItems: "stretch",
    paddingHorizontal: 16,
    paddingTop: "20%",
    backgroundColor: "#fff",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  logWrapper: {
    marginTop: "auto",
    position: "relative",
    alignItems: "stretch",
    paddingHorizontal: 16,
    paddingTop: "20%",
    backgroundColor: "#fff",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  avatarWrap: {
    position: "absolute",
    display: "flex",
    top: -60,
    alignSelf: "center",
    backgroundColor: "#F6F6F6",
    width: 120,
    height: 120,
    borderRadius: 16,
  },
  addAvaBtn: {
    position: "absolute",
    bottom: 14,
    right: -12,
  },
  title: {
    fontSize: 30,
    fontWeight: "500",
    textAlign: "center",
    marginBottom: 32,
  },
  input: {
    padding: 16,
    fontSize: 16,
    backgroundColor: "#F6F6F6",
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 16,
  },
  passwordWrap: {
    position: "relative",
  },
  showBtn: {
    position: "absolute",
    display: "flex",
    right: 16,
    top: 16,
    height: "100%",
    fontSize: 16,
    color: "#fff",
  },
  showBtnText: {
    fontSize: 16,
    color: "#1B4371",
  },
  linkText: {
    padding: 16,
    fontSize: 16,
    textAlign: "center",
    color: "#1B4371",
  },
});
