import { StyleSheet } from "react-native";

export const additionalStyles = StyleSheet.create({
  screenWrap: {
    backgroundColor: "#FFF",
    height: "100%",
    display: "flex",
  },
  photoWrap: {
    height: 240,
    backgroundColor: "#F6F6F6",
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
  },
  comWrap: {
    backgroundColor: "#FFF",
    paddingHorizontal: "4%",
    paddingVertical: "7%",
    display: "flex",
    marginBottom: 52,
  },
  comContainer: {
    display: "flex",
    justifyContent: "space-between",
    flexWrap: "nowrap",
    width: "100%",
  },
  com: {
    padding: 16,
    backgroundColor: "#F6F6F6",
    borderRadius: 6,
    marginBottom: 16,
    flexGrow: 1,
    maxWidth: "88%",
  },
  dateText: {
    fontSize: 10,
    color: "#BDBDBD",
    marginTop: 8,
    marginLeft: "auto",
  },
  commentAva: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F6F6F6",
  },
  inputWrap: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    bottom: 0,
    paddingVertical: 16,
    backgroundColor: "#FFF",
    width: "100%",
  },
  input: {
    borderWidth: 1,
    fontSize: 16,
    fontWeight: "500",
    backgroundColor: "#F6F6F6",
    height: 50,
    borderRadius: 25,
    width: "92%",
    paddingLeft: 16,
    paddingRight: 51,
  },
  inputBtn: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    right: "7%",
    top: 24,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#FF6C00",
  },
});
